2020-03-10 14:44:30,129D:/Py Charm/WeChat_app/apis/test_log.py : log_demo
2020-03-10 14:44:30,129D:/Py Charm/WeChat_app/apis/test_log.py : log_demo
2020-03-10 15:23:25,846D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\log.py : log_response
2020-03-10 15:23:25,847D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\servers\basehttp.py : log_message
2020-03-10 15:23:25,963D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\log.py : log_response
2020-03-10 15:23:25,967D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\servers\basehttp.py : log_message
2020-03-10 15:37:56,798D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\log.py : log_response
Traceback (most recent call last):
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'wechat.index__menu' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1582, in _changeform_view
    form = ModelForm(instance=obj)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\forms\models.py", line 293, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\forms\models.py", line 93, in model_to_dict
    data[f.name] = f.value_from_object(instance)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\fields\related.py", line 1615, in value_from_object
    return [] if obj.pk is None else list(getattr(obj, self.attname).all())
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\query.py", line 276, in __iter__
    self._fetch_all()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1144, in execute_sql
    cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'wechat.index__menu' doesn't exist")
2020-03-10 15:37:56,805D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\servers\basehttp.py : log_message
2020-03-10 15:46:56,201D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\log.py : log_response
Traceback (most recent call last):
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '' for key 'openid'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "D:\Py Charm\WeChat_app\apis\admin.py", line 17, in save_model
    return super(UserAdmin, self).save_model(request, obj, form, change)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\contrib\admin\options.py", line 1081, in save_model
    obj.save()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\base.py", line 784, in save_base
    force_update, using, update_fields,
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1384, in execute_sql
    cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\Py Charm\WeChat_app\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '' for key 'openid'")
2020-03-10 15:46:56,209D:\Py Charm\WeChat_app\venv\lib\site-packages\django\core\servers\basehttp.py : log_message
